"""
Attack Plan Data Models

Defines the schema for security testing attack plans generated by the Planner agent.
These plans provide step-by-step strategies for testing AI systems against
OWASP LLM Top 10 vulnerabilities.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator
from uuid import uuid4

from .payload import AttackCategory, ComplexityLevel, PayloadTemplate


class PlanStatus(str, Enum):
    """Status of an attack plan."""
    DRAFT = "draft"
    READY = "ready"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    FAILED = "failed"


class PriorityLevel(str, Enum):
    """Priority levels for attack steps."""
    CRITICAL = "critical"  # Must test - high impact, high likelihood
    HIGH = "high"  # Important - high impact or high likelihood
    MEDIUM = "medium"  # Moderate risk
    LOW = "low"  # Nice to have if time permits


class TimingStrategy(str, Enum):
    """Timing strategies for attack execution."""
    IMMEDIATE = "immediate"  # Execute right away
    SEQUENTIAL = "sequential"  # Execute in order, one after another
    PARALLEL = "parallel"  # Execute simultaneously
    CONDITIONAL = "conditional"  # Based on previous results
    STAGED = "staged"  # Multi-stage with pauses between


class MultiTurnStrategy(BaseModel):
    """
    Strategy for multi-turn attack sequences.

    Multi-turn attacks require multiple interactions with the target
    to achieve the objective (e.g., building trust, probing defenses).
    """
    strategy_type: str = Field(
        ...,
        description="Type of multi-turn strategy (e.g., 'gradual_escalation', 'context_injection')"
    )
    turn_count: int = Field(
        ...,
        ge=1,
        le=10,
        description="Number of turns in this attack sequence"
    )
    turn_descriptions: List[str] = Field(
        default_factory=list,
        description="Description of each turn in the sequence"
    )
    success_criteria: List[str] = Field(
        default_factory=list,
        description="Criteria that indicate success at each turn"
    )
    abort_triggers: List[str] = Field(
        default_factory=list,
        description="Conditions that should abort the sequence"
    )
    maintain_context: bool = Field(
        default=True,
        description="Whether to maintain conversation context across turns"
    )


class AttackStep(BaseModel):
    """
    A single step in an attack plan.

    Each step represents one payload delivery or probing action
    with its own timing, success criteria, and fallback options.
    """
    step_id: str = Field(default_factory=lambda: str(uuid4()))
    step_number: int = Field(..., ge=1, description="Sequential order of this step")

    # Identification
    name: str = Field(..., min_length=1, max_length=200)
    description: str = Field(..., min_length=1, max_length=1000)

    # Attack categorization
    attack_category: AttackCategory
    subcategory: Optional[str] = None

    # Payload configuration
    payload_template_id: Optional[str] = Field(
        None,
        description="ID of payload template to use"
    )
    payload_template: Optional[PayloadTemplate] = None
    payload_variables: Dict[str, Any] = Field(
        default_factory=dict,
        description="Variable values for payload template"
    )

    # Priority and complexity
    priority: PriorityLevel = PriorityLevel.MEDIUM
    complexity: ComplexityLevel = ComplexityLevel.BASIC

    # Timing
    timing: TimingStrategy = TimingStrategy.IMMEDIATE
    delay_seconds: Optional[float] = Field(
        None,
        ge=0,
        description="Delay before executing this step"
    )
    depends_on: List[str] = Field(
        default_factory=list,
        description="Step IDs that must complete before this step"
    )

    # Multi-turn configuration
    multi_turn_strategy: Optional[MultiTurnStrategy] = None

    # Success/failure handling
    success_criteria: List[str] = Field(
        default_factory=list,
        description="Conditions indicating successful attack"
    )
    failure_indicators: List[str] = Field(
        default_factory=list,
        description="Responses or behaviors indicating failure"
    )
    retry_on_failure: bool = True
    max_retries: int = Field(default=3, ge=0, le=10)

    # Expected outcomes
    expected_outcome: str = Field(
        ...,
        description="Expected result if attack succeeds"
    )
    secondary_indicators: List[str] = Field(
        default_factory=list,
        description="Other signals that may indicate partial success"
    )

    # Risk and constraints
    risk_level: str = Field(
        default="medium",
        pattern="^(low|medium|high|critical)$"
    )
    side_effects: List[str] = Field(
        default_factory=list,
        description="Potential side effects of this attack step"
    )

    # Metadata
    notes: Optional[str] = None
    references: List[str] = Field(
        default_factory=list,
        description="Links to research or similar attacks"
    )

    @field_validator("depends_on")
    @classmethod
    def validate_dependencies(cls, v: List[str]) -> List[str]:
        """Ensure dependency list doesn't contain duplicates."""
        return list(dict.fromkeys(v))  # Preserve order while deduplicating


class AttackPlan(BaseModel):
    """
    Complete attack plan for security testing.

    An attack plan is a structured approach to testing an AI system,
    generated by the Planner agent based on Analyst findings.
    It includes multiple attack steps with timing, priorities,
    and multi-turn sequences.
    """
    # Core identification
    plan_id: str = Field(default_factory=lambda: str(uuid4()))
    name: str = Field(..., min_length=1, max_length=200)
    description: str = Field(..., min_length=1, max_length=2000)

    # Status and versioning
    status: PlanStatus = PlanStatus.DRAFT
    version: str = "1.0.0"
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # Context
    session_id: str = Field(..., description="Session this plan belongs to")
    campaign_id: Optional[str] = Field(None, description="Campaign if part of larger operation")
    target_system: Optional[str] = Field(None, description="Description of target system")

    # Source analysis
    source_analysis_id: Optional[str] = Field(
        None,
        description="ID of the analysis that generated this plan"
    )
    source_agent: str = Field(
        default="planner",
        description="Agent that created this plan"
    )

    # Attack steps
    attack_steps: List[AttackStep] = Field(
        default_factory=list,
        description="Ordered list of attack steps"
    )

    # Overall strategy
    overall_strategy: str = Field(
        ...,
        description="High-level approach and rationale"
    )
    success_criteria: List[str] = Field(
        default_factory=list,
        description="Overall success criteria for the plan"
    )

    # Risk assessment
    overall_risk_level: str = Field(
        default="medium",
        pattern="^(low|medium|high|critical)$"
    )
    estimated_duration_hours: Optional[float] = Field(
        None,
        ge=0,
        description="Estimated time to complete all steps"
    )

    # Scope and constraints
    scope_limitations: List[str] = Field(
        default_factory=list,
        description="What NOT to test (explicitly out of scope)"
    )
    constraints: List[str] = Field(
        default_factory=list,
        description="Constraints on testing (time, access, etc.)"
    )

    # Framework mappings for compliance
    framework_mappings: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="Mappings to OWASP ASI, MITRE ATLAS, etc."
    )

    # Tags and metadata
    tags: List[str] = Field(default_factory=list)
    llm_model: str = Field(default="planner-agent", description="Model used to generate plan")
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @field_validator("attack_steps")
    @classmethod
    def validate_attack_steps(cls, v: List[AttackStep]) -> List[AttackStep]:
        """Validate attack steps are properly ordered and dependencies exist."""
        if not v:
            return v

        # Check step numbers are sequential starting from 1
        step_numbers = sorted([step.step_number for step in v])
        expected = list(range(1, len(v) + 1))
        if step_numbers != expected:
            raise ValueError(f"Step numbers must be sequential from 1 to {len(v)}")

        # Check all dependencies reference existing steps
        step_ids = {step.step_id for step in v}
        for step in v:
            for dep_id in step.depends_on:
                if dep_id not in step_ids:
                    raise ValueError(f"Step {step.step_number} depends on non-existent step ID: {dep_id}")

        return v

    def get_step_by_id(self, step_id: str) -> Optional[AttackStep]:
        """Get an attack step by its ID."""
        for step in self.attack_steps:
            if step.step_id == step_id:
                return step
        return None

    def get_steps_by_priority(self, priority: PriorityLevel) -> List[AttackStep]:
        """Get all steps with a specific priority level."""
        return [step for step in self.attack_steps if step.priority == priority]

    def get_next_executable_step(self, completed_step_ids: List[str]) -> Optional[AttackStep]:
        """
        Get the next step that can be executed based on completed steps.

        Args:
            completed_step_ids: List of step IDs that have been completed

        Returns:
            Next executable step or None if no more steps can be executed
        """
        completed_set = set(completed_step_ids)

        for step in sorted(self.attack_steps, key=lambda s: s.step_number):
            if step.step_id in completed_set:
                continue

            # Check if all dependencies are met
            if all(dep_id in completed_set for dep_id in step.depends_on):
                return step

        return None

    def get_execution_summary(self) -> Dict[str, Any]:
        """Get a summary of the plan for execution."""
        return {
            "plan_id": self.plan_id,
            "name": self.name,
            "total_steps": len(self.attack_steps),
            "by_priority": {
                "critical": len(self.get_steps_by_priority(PriorityLevel.CRITICAL)),
                "high": len(self.get_steps_by_priority(PriorityLevel.HIGH)),
                "medium": len(self.get_steps_by_priority(PriorityLevel.MEDIUM)),
                "low": len(self.get_steps_by_priority(PriorityLevel.LOW)),
            },
            "by_category": self._count_by_category(),
            "estimated_duration_hours": self.estimated_duration_hours,
            "overall_risk_level": self.overall_risk_level,
        }

    def _count_by_category(self) -> Dict[str, int]:
        """Count steps by attack category."""
        counts: Dict[str, int] = {}
        for step in self.attack_steps:
            category = step.attack_category.value
            counts[category] = counts.get(category, 0) + 1
        return counts


class PlanCreateRequest(BaseModel):
    """Request to create a new attack plan."""

    name: str = Field(..., min_length=1, max_length=200)
    description: str = Field(..., min_length=1, max_length=2000)
    session_id: str = Field(..., description="Session ID")
    campaign_id: Optional[str] = None
    target_system: Optional[str] = None

    # Source analysis
    source_analysis_id: Optional[str] = None
    analysis_data: Optional[Dict[str, Any]] = Field(
        None,
        description="Raw analysis data from Analyst agent"
    )

    # Constraints
    scope_limitations: List[str] = Field(default_factory=list)
    constraints: List[str] = Field(default_factory=list)
    max_duration_hours: Optional[float] = Field(None, ge=0)

    # Preferences
    preferred_complexity: Optional[ComplexityLevel] = None
    include_multi_turn: bool = True
    max_steps: Optional[int] = Field(None, ge=1, le=50)


class PlanUpdateRequest(BaseModel):
    """Request to update an existing attack plan."""

    name: Optional[str] = None
    description: Optional[str] = None
    status: Optional[PlanStatus] = None
    attack_steps: Optional[List[AttackStep]] = None
    success_criteria: Optional[List[str]] = None
    scope_limitations: Optional[List[str]] = None
    constraints: Optional[List[str]] = None
    estimated_duration_hours: Optional[float] = None


class PlanExecutionState(BaseModel):
    """
    Current state of plan execution.

    Tracks progress through the attack plan, recording
    which steps have been completed and their results.
    """
    execution_id: str = Field(default_factory=lambda: str(uuid4()))
    plan_id: str = Field(..., description="ID of the plan being executed")
    session_id: str = Field(..., description="Session ID")

    # Execution tracking
    status: PlanStatus = PlanStatus.IN_PROGRESS
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None

    # Step progress
    completed_step_ids: List[str] = Field(
        default_factory=list,
        description="Steps that have been completed"
    )
    failed_step_ids: List[str] = Field(
        default_factory=list,
        description="Steps that failed"
    )
    skipped_step_ids: List[str] = Field(
        default_factory=list,
        description="Steps that were skipped"
    )

    # Results
    step_results: Dict[str, Dict[str, Any]] = Field(
        default_factory=dict,
        description="Results from each completed step (step_id -> result)"
    )

    # Overall assessment
    vulnerabilities_found: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Vulnerabilities discovered during execution"
    )
    overall_success: Optional[bool] = Field(
        None,
        description="Whether the plan achieved its objectives"
    )
    execution_notes: List[str] = Field(
        default_factory=list,
        description="Notes and observations during execution"
    )

    def get_progress_percentage(self) -> float:
        """Calculate progress as percentage of steps completed."""
        total_steps = (
            len(self.completed_step_ids) +
            len(self.failed_step_ids) +
            len(self.skipped_step_ids)
        )
        # This would need the total steps from the plan
        # For now, return a placeholder
        return 0.0

    def get_summary(self) -> Dict[str, Any]:
        """Get execution summary."""
        return {
            "execution_id": self.execution_id,
            "plan_id": self.plan_id,
            "status": self.status.value,
            "started_at": self.started_at.isoformat(),
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "steps_completed": len(self.completed_step_ids),
            "steps_failed": len(self.failed_step_ids),
            "steps_skipped": len(self.skipped_step_ids),
            "vulnerabilities_found": len(self.vulnerabilities_found),
            "overall_success": self.overall_success,
        }
